# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE
  machineType: E2_HIGHCPU_8

substitutions:
  _AR_REGION: asia-south1
  _AR_REPO: web
  _SERVICE: bitpers-site
  _RUN_REGION: asia-southeast1
  _RUNTIME_SA: bitpers-web@bitpers-75854.iam.gserviceaccount.com

steps:
  # 1) Build container
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$SHORT_SHA
      - .

  # 2) Push image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$SHORT_SHA

  # 3) Deploy to Cloud Run (asia-southeast1)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$SHORT_SHA
      - --region=${_RUN_REGION}
      - --service-account=${_RUNTIME_SA}
      - --allow-unauthenticated
      # keep your current autoscaling/memory/cpu/concurrency if you like:
      # - --min-instances=0
      # - --max-instances=3
      # - --memory=512Mi
      # - --cpu=1
      # - --concurrency=80

images:
  - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$SHORT_SHA

timeout: "1200s"
